-- Portfolio enhancement migration — additive only, safe to re-run.
-- Run in Supabase SQL Editor after the base README script.

-- 1. Rate-limit ledger for submit-comment edge function
CREATE TABLE IF NOT EXISTS public.comment_rate_limits (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ip_hash text NOT NULL,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE public.comment_rate_limits ENABLE ROW LEVEL SECURITY;
-- No public policies: service_role only (edge function). Anon gets nothing.

-- 2. Showcase enrichments (all nullable/additive)
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS slug text UNIQUE;
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS impact text;
ALTER TABLE public.experiences ADD COLUMN IF NOT EXISTS employment_type text;
ALTER TABLE public.experiences ADD COLUMN IF NOT EXISTS skills text[];
ALTER TABLE public.certificates ADD COLUMN IF NOT EXISTS issuer text;
ALTER TABLE public.certificates ADD COLUMN IF NOT EXISTS issued_at date;
ALTER TABLE public.certificates ADD COLUMN IF NOT EXISTS verify_url text;

-- 3. Privacy-friendly analytics (no PII, coarse counts only)
CREATE TABLE IF NOT EXISTS public.portfolio_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event text NOT NULL,
  path text,
  meta jsonb,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE public.portfolio_events ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "public insert events" ON public.portfolio_events;
CREATE POLICY "public insert events"
ON public.portfolio_events FOR INSERT
WITH CHECK (event IN ('contact_submit','cv_view','cv_download','project_click','project_detail_view','github_click'));

-- 4. CV storage bucket (code uses cv-documents with public URLs)
INSERT INTO storage.buckets (id, name, public)
VALUES ('cv-documents', 'cv-documents', true)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "public read cv documents" ON storage.objects;
CREATE POLICY "public read cv documents"
ON storage.objects FOR SELECT
USING (bucket_id = 'cv-documents');

DROP POLICY IF EXISTS "admin upload cv documents" ON storage.objects;
CREATE POLICY "admin upload cv documents"
ON storage.objects FOR INSERT
WITH CHECK (
  bucket_id = 'cv-documents'
  AND EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);

DROP POLICY IF EXISTS "admin update cv documents" ON storage.objects;
CREATE POLICY "admin update cv documents"
ON storage.objects FOR UPDATE
USING (
  bucket_id = 'cv-documents'
  AND EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);

DROP POLICY IF EXISTS "admin delete cv documents" ON storage.objects;
CREATE POLICY "admin delete cv documents"
ON storage.objects FOR DELETE
USING (
  bucket_id = 'cv-documents'
  AND EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);

-- 5. Missing storage UPDATE/DELETE for existing image buckets
DROP POLICY IF EXISTS "admin update project images" ON storage.objects;
CREATE POLICY "admin update project images"
ON storage.objects FOR UPDATE
USING (
  bucket_id = 'project-images'
  AND EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);
DROP POLICY IF EXISTS "admin delete project images" ON storage.objects;
CREATE POLICY "admin delete project images"
ON storage.objects FOR DELETE
USING (
  bucket_id = 'project-images'
  AND EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);
DROP POLICY IF EXISTS "admin update certificate images" ON storage.objects;
CREATE POLICY "admin update certificate images"
ON storage.objects FOR UPDATE
USING (
  bucket_id = 'certificate-images'
  AND EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);
DROP POLICY IF EXISTS "admin delete certificate images" ON storage.objects;
CREATE POLICY "admin delete certificate images"
ON storage.objects FOR DELETE
USING (
  bucket_id = 'certificate-images'
  AND EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);
DROP POLICY IF EXISTS "admin update svg assets" ON storage.objects;
CREATE POLICY "admin update svg assets"
ON storage.objects FOR UPDATE
USING (
  bucket_id = 'svg-assets'
  AND EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);
